 # This is a format showing how to use separate Ingress resources for each service
 # it works properly for both Prometheus and Grafana and otel with subpath support.
 # we will have three Ingress resources defined below. but all of them point to the same host.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: demo123.swedencentral.cloudapp.azure.com
    http:
      paths:
      - path: "/prometheus(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus
            port:
              number: 9090
---
# Separate Ingress for Grafana
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: demo123.swedencentral.cloudapp.azure.com
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
---
# Separate Ingress for OTel Collector
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-ingress
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
  - host: demo123.swedencentral.cloudapp.azure.com
    http:
      paths:
      - path: "/collector(/|$)(.*)"
        pathType: ImplementationSpecific
        backend:
          service:
            name: otel-collector
            port:
              number: 4318