# Gateway API Gateway definition for Observability Stack
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: observability-gateway
  namespace: observability
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: demo-gateway.swedencentral.cloudapp.azure.com
